### ISSUE TITLE
Import error for module _bsddb

### ISSUE THREAD

**Issue by AlexaVillaume** [astropy/astroplan#114]
Hi everyone,

I installed astroplan using conda (Python 2.7 on a macbook pro with OS X 10.9.5). Nothing seemed to go wrong in the installation but when I try ```import astroplan``` I get the following error,

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alexawork/anaconda/lib/python2.7/site-packages/astroplan/__init__.py", line 31, in <module>
    get_IERS_A_or_workaround()
  File "/Users/alexawork/anaconda/lib/python2.7/site-packages/astroplan/utils.py", line 52, in get_IERS_A_or_workaround
    if IERS_A_in_cache():
  File "/Users/alexawork/anaconda/lib/python2.7/site-packages/astroplan/utils.py", line 72, in IERS_A_in_cache
    with _open_shelve(urlmapfn, True) as url2hash:
  File "/Users/alexawork/anaconda/lib/python2.7/site-packages/astropy/utils/data.py", line 1214, in _open_shelve
    shelf = shelve.open(shelffn, protocol=2)
  File "/Users/alexawork/anaconda/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/Users/alexawork/anaconda/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/Users/alexawork/anaconda/lib/python2.7/anydbm.py", line 84, in open
    mod = __import__(result)
  File "/Users/alexawork/anaconda/lib/python2.7/dbhash.py", line 7, in <module>
    import bsddb
  File "/Users/alexawork/anaconda/lib/python2.7/bsddb/__init__.py", line 67, in <module>
    import _bsddb
ImportError: No module named _bsddb```

I'm not sure if this is an issue that's specific to my setup, the module bsddb is in my anaconda package but it doesn't have a file _bsddb. Should my installation have that file?

Thank you,
Alexa

**Comment by adrn** [comment]
Huhm, that's odd. Can you `ls -l /Users/alexawork/anaconda/lib/python2.7/bsddb/` and see if there is a `_bsddb.so` file there?

[This thread](https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/mCQL6fVx55A) seems to suggest it could be an anaconda issue -- have you tried `conda install bsddb`?

**Comment by eteq** [comment]
I encountered exactly the same problem a while back while testing with conda, and indeed I fixed it as @adrn suggests via `` conda install bsddb``.  So hopefully that will do the trick.

Just so we can be sure, though, @AlexaVillaume, can you try doing an identical environment but *not* install astroplan, and instead just have it install `astropy`.  Then see if you see the error on ``import astropy``.  If yes, it's conda's problem (astropy uses the `shelve` python standard library module, which uses `bsddb`)... But we should probably mention it on the *astropy* known issues page because it's quite reasonable for users to conclude just what you did here, @AlexaVillaume.

**Comment by AlexaVillaume** [comment]
Thank you @adrn and @eteq for responding to me. I did check and the _bsddb.so file wasn't there. However, I didn't get a chance to try your solution because my computer died  ¯\_(ツ)_/¯. 

For what it's worth, I did install astroplan on what should be an identical set up on a different computer and it worked fine. I ran the tests with no errors and I'm looking forward to trying it out!

**Comment by bmorris3** [comment]
Great, then I'll close the issue. Enjoy :+1:
