### ISSUE TITLE
IERS update failing

### ISSUE THREAD

**Issue by iwellaway** [astropy/astroplan#428]
Hi,

I'm getting the following error when trying to update IERS:

(venv) ian@vera:/opt/webs/vera.astro.ex.ac.uk/wsgi/harps3$ python
Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from astroplan import download_IERS_A
>>> download_IERS_A()
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 946, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/webs/vera.astro.ex.ac.uk/wsgi/harps3/venv/lib/python3.6/site-packages/astroplan/utils.py", line 126, in download_IERS_A
    show_progress=show_progress)
  File "/opt/webs/vera.astro.ex.ac.uk/wsgi/harps3/venv/lib/python3.6/site-packages/astropy/utils/data.py", line 1091, in download_file
    raise e
  File "/opt/webs/vera.astro.ex.ac.uk/wsgi/harps3/venv/lib/python3.6/site-packages/astropy/utils/data.py", line 1024, in download_file
    with urllib.request.urlopen(remote_url, timeout=timeout) as remote:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
>>> 

This is quite serious as it's stopped everything working. I first noticed it yesterday (about 18 hours ago) but hoped it would fix itself.

I'm not getting any response from the following sites:
http://maia.usno.navy.mil/
http://toshi.nofs.navy.mil/

I recognise that this might be 'upstream' but am not sure how to proceed?

Cheers

Ian

**Comment by bmorris3** [comment]
Hi Ian – check out the issues #425 and #427 for temporary fixes, or upgrade to the latest (dev) version of astropy for the long-term patch. Let me know when everything's fixed.

**Comment by iwellaway** [comment]
@bmorris3 Brilliant, just ran the patch in #425 then upgraded to astropy 3.2.3 and it's working again now. I'll add this to my 'things to do when stuff breaks' list!

Thank you very much for your speedy response.

**Comment by bmorris3** [comment]
Anytime!

**Comment by bmorris3** [comment]
Anytime!

**Comment by iwellaway** [comment]
Hi Brett,

We're a bit concerned about missing this sort of event where things stop working when our project starts and the scheduler goes into production. Is there a way to stay up to date with events such as this, like a feed or a group so we could stay informed and act pre-emptively beforehand?

On the same note, is there a local version of the ephemeris file (like the one that got relocated and so caused the issue) that could be used by the astropy functions in an emergency?

Let me know what you think.

Thanks a lot.

Ian

**Comment by bmorris3** [comment]
The best way would be to subscribe to notifications on the astroplan github page, by clicking the "watch" button in the upper right corner of the repo page. That way you can get emails when issues are posted. An additional/alternative option would be to join the [astropy slack page](http://joinslack.astropy.org), where you can get real time support from many astropy developers including me. I've just created an _astroplan_ channel for this purpose. Feel free to join it and subscribe to notifications there as well.

There is no copy of the IERS tables being hosted anywhere [because we're not allowed](https://github.com/astropy/astroplan/issues/410#issuecomment-503340938) to host such a copy without permission.

**Comment by iwellaway** [comment]
Thanks Brett, I’ll do that.

Best regards

Ian
