### ISSUE TITLE
get_IERS_A_or_workaround(): ValueError: Column year failed to convert: invalid literal for int() with base 10: '\ufeff<'

### ISSUE THREAD

**Issue by ziggyman** [astropy/astroplan#450]
when importing Observer from astroplan I get:
Traceback (most recent call last):
  File "/Users/azuri/anaconda3/envs/python3env/lib/python3.6/site-packages/astropy/io/ascii/core.py", line 955, in _convert_vals
    converter_func, converter_type = col.converters[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "findTargets.py", line 1, in <module>
    from astroplan import Observer
  File "/Users/azuri/anaconda3/envs/python3env/lib/python3.6/site-packages/astroplan/__init__.py", line 32, in <module>
    get_IERS_A_or_workaround()
  File "/Users/azuri/anaconda3/envs/python3env/lib/python3.6/site-packages/astroplan/utils.py", line 58, in get_IERS_A_or_workaround
    iers.IERS.iers_table = _get_IERS_A_table()
  File "/Users/azuri/anaconda3/envs/python3env/lib/python3.6/site-packages/astroplan/utils.py", line 93, in _get_IERS_A_table
    table = iers.IERS_Auto.open()
  File "/Users/azuri/anaconda3/envs/python3env/lib/python3.6/site-packages/astropy/utils/iers/iers.py", line 660, in open
    cls.iers_table = cls.read(file=filename)
  File "/Users/azuri/anaconda3/envs/python3env/lib/python3.6/site-packages/astropy/utils/iers/iers.py", line 504, in read
    iers_a = Table.read(file, format='cds', readme=readme)
  File "/Users/azuri/anaconda3/envs/python3env/lib/python3.6/site-packages/astropy/table/connect.py", line 52, in __call__
    out = registry.read(cls, *args, **kwargs)
  File "/Users/azuri/anaconda3/envs/python3env/lib/python3.6/site-packages/astropy/io/registry.py", line 523, in read
    data = reader(*args, **kwargs)
  File "/Users/azuri/anaconda3/envs/python3env/lib/python3.6/site-packages/astropy/io/ascii/connect.py", line 19, in io_read
    return read(filename, **kwargs)
  File "/Users/azuri/anaconda3/envs/python3env/lib/python3.6/site-packages/astropy/io/ascii/ui.py", line 323, in read
    dat = reader.read(table)
  File "/Users/azuri/anaconda3/envs/python3env/lib/python3.6/site-packages/astropy/io/ascii/cds.py", line 326, in read
    return super().read(table)
  File "/Users/azuri/anaconda3/envs/python3env/lib/python3.6/site-packages/astropy/io/ascii/core.py", line 1207, in read
    table = self.outputter(cols, self.meta)
  File "/Users/azuri/anaconda3/envs/python3env/lib/python3.6/site-packages/astropy/io/ascii/core.py", line 986, in __call__
    self._convert_vals(cols)
  File "/Users/azuri/anaconda3/envs/python3env/lib/python3.6/site-packages/astropy/io/ascii/core.py", line 971, in _convert_vals
    raise ValueError('Column {} failed to convert: {}'.format(col.name, last_err))
ValueError: Column year failed to convert: invalid literal for int() with base 10: '\ufeff<'

**Comment by bmorris3** [comment]
Please update to the latest version of astropy and astroplan and let me know if you get the same error. I believe this issue is fixed for newer versions.

**Comment by ziggyman** [comment]
after upgrading to the latest version of astropy it seems to work. Closing the issue again
