### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by christianhannah** [astropy/astroplan#454]
Upon executing the script (http://github.com/anilseth/astr6410), the following error is being encountered. This error is occurring on multiple machines (both MasOS and Windows). All machines are using the following packages/versions: astroplan/0.6, python/3.7.4, anaconda/2019.10, spyder/3.3.6, and astropy/3.2.1. I should note that half of the computers attempting this received no error (again both MacOS and Windows with identical packages and versions).

The specific line in the program that appears to be generating the error is line 32:
"plot_airmass(betelgeuse, slc, time, brightness_shading=True, altitude_yaxis=True)"
 
Excerpt from Spyder:
__________________________________________________________________________________________
In [5]: runfile('C:/Users/Christian/Documents/Python Scripts/astroplan_example.py', wdir='C:/Users/Christian/Documents/Python Scripts')

WARNING: failed to download http://maia.usno.navy.mil/ser7/finals2000A.all and http://toshi.nofs.navy.mil/ser7/finals2000A.all, using local IERS-B: [WinError 10054] An existing connection was forcibly closed by the remote host;<urlopen error [Errno 11001] getaddrinfo failed> [astropy.utils.iers.iers]
WARNING: Tried to get polar motions for times after IERS data is valid. Defaulting to polar motion from the 50-yr mean for those. This may affect precision at the 10s of arcsec level [astropy.coordinates.builtin_frames.utils]
WARNING: failed to download http://maia.usno.navy.mil/ser7/finals2000A.all and http://toshi.nofs.navy.mil/ser7/finals2000A.all, using local IERS-B: [WinError 10054] An existing connection was forcibly closed by the remote host;<urlopen error [Errno 11002] getaddrinfo failed> [astropy.utils.iers.iers]
WARNING: (some) times are outside of range covered by IERS table. Assuming UT1-UTC=0 for coordinate transformations. [astropy.coordinates.builtin_frames.utils]
Traceback (most recent call last):

File "<ipython-input-5-99a1a1f7321b>", line 1, in <module>
    runfile('C:/Users/Christian/Documents/Python Scripts/astroplan_example.py', wdir='C:/Users/Christian/Documents/Python Scripts')

  File "C:\Users\Christian\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\Christian\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Christian/Documents/Python Scripts/astroplan_example.py", line 32, in <module>
    plot_airmass(betelgeuse, slc, time, brightness_shading=True, altitude_yaxis=True)

  File "C:\Users\Christian\Anaconda3\lib\site-packages\astroplan\plots\time_dependent.py", line 193, in plot_airmass
    (observer.sun_set_time(Time(start), which='next').datetime, 0.0),

  File "C:\Users\Christian\Anaconda3\lib\site-packages\astropy\units\decorators.py", line 222, in wrapper
    return_ = wrapped_function(*func_args, **func_kwargs)

  File "C:\Users\Christian\Anaconda3\lib\site-packages\astroplan\observer.py", line 1288, in sun_set_time
    n_grid_points=n_grid_points)

  File "C:\Users\Christian\Anaconda3\lib\site-packages\astropy\units\decorators.py", line 222, in wrapper
    return_ = wrapped_function(*func_args, **func_kwargs)

  File "C:\Users\Christian\Anaconda3\lib\site-packages\astroplan\observer.py", line 1065, in target_set_time
    grid_times_targets=grid_times_targets))

  File "C:\Users\Christian\Anaconda3\lib\site-packages\astroplan\observer.py", line 916, in _determine_which_event
    next_event = event_function('next')

  File "C:\Users\Christian\Anaconda3\lib\site-packages\astroplan\observer.py", line 902, in event_function
    n_grid_points=n_grid_points)

  File "C:\Users\Christian\Anaconda3\lib\site-packages\astroplan\observer.py", line 799, in _calc_riseset
    grid_times_targets=grid_times_targets)

  File "C:\Users\Christian\Anaconda3\lib\site-packages\astroplan\observer.py", line 496, in altaz
    return target.transform_to(altaz_frame)

  File "C:\Users\Christian\Anaconda3\lib\site-packages\astropy\coordinates\sky_coordinate.py", line 443, in transform_to
    new_coord = trans(self.frame, generic_frame)

  File "C:\Users\Christian\Anaconda3\lib\site-packages\astropy\coordinates\transformations.py", line 1377, in __call__
    curr_coord = t(curr_coord, curr_toframe)

  File "C:\Users\Christian\Anaconda3\lib\site-packages\astropy\coordinates\transformations.py", line 980, in __call__
    return supcall(fromcoord, toframe)

  File "C:\Users\Christian\Anaconda3\lib\site-packages\astropy\coordinates\builtin_frames\cirs_observed_transforms.py", line 44, in cirs_to_altaz
    loccirs = altaz_frame.location.get_itrs(cirs_coo.obstime).transform_to(cirs_coo)

  File "C:\Users\Christian\Anaconda3\lib\site-packages\astropy\coordinates\baseframe.py", line 1186, in transform_to
    return trans(self, new_frame)

  File "C:\Users\Christian\Anaconda3\lib\site-packages\astropy\coordinates\transformations.py", line 1377, in __call__
    curr_coord = t(curr_coord, curr_toframe)

  File "C:\Users\Christian\Anaconda3\lib\site-packages\astropy\coordinates\transformations.py", line 980, in __call__
    return supcall(fromcoord, toframe)

  File "C:\Users\Christian\Anaconda3\lib\site-packages\astropy\coordinates\builtin_frames\intermediate_rotation_transforms.py", line 87, in itrs_to_cirs
    pmat = cirs_to_itrs_mat(itrs_coo.obstime)

  File "C:\Users\Christian\Anaconda3\lib\site-packages\astropy\coordinates\builtin_frames\intermediate_rotation_transforms.py", line 37, in cirs_to_itrs_mat
    era = erfa.era00(*get_jd12(time, 'ut1'))

  File "C:\Users\Christian\Anaconda3\lib\site-packages\astropy\coordinates\builtin_frames\utils.py", line 111, in get_jd12
    newtime = getattr(time, scale)

  File "C:\Users\Christian\Anaconda3\lib\site-packages\astropy\time\core.py", line 1528, in __getattr__
    tm._set_scale(attr)

  File "C:\Users\Christian\Anaconda3\lib\site-packages\astropy\time\core.py", line 718, in _set_scale
    args.append(get_dt(jd1, jd2))

  File "C:\Users\Christian\Anaconda3\lib\site-packages\astroplan\utils.py", line 41, in _low_precision_utc_to_ut1
    if self.mjd*u.day not in iers.IERS_Auto.open()['MJD']:

  File "C:\Users\Christian\Anaconda3\lib\site-packages\astropy\utils\iers\iers.py", line 643, in open
    filename = download_file(url, cache=True)

  File "C:\Users\Christian\Anaconda3\lib\site-packages\astropy\utils\iers\iers.py", line 79, in download_file
    return utils.data.download_file(*args, **kwargs)

  File "C:\Users\Christian\Anaconda3\lib\site-packages\astropy\utils\data.py", line 1024, in download_file
    with urllib.request.urlopen(remote_url, timeout=timeout) as remote:

  File "C:\Users\Christian\Anaconda3\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)

  File "C:\Users\Christian\Anaconda3\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)

  File "C:\Users\Christian\Anaconda3\lib\urllib\request.py", line 543, in _open
    '_open', req)

  File "C:\Users\Christian\Anaconda3\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)

  File "C:\Users\Christian\Anaconda3\lib\urllib\request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)

  File "C:\Users\Christian\Anaconda3\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))

KeyboardInterrupt
___________________________________________________________________________________________

The following download was attempted as a possible fix to this issue, and another error was encountered (shown below) 

Excerpt from Spyder:
______________________________________________________________________________________________
In [6]: download_IERS_A()
Traceback (most recent call last):

  File "<ipython-input-4-3953bedb3d4d>", line 1, in <module>
    download_IERS_A()

  File "C:\Users\Christian\Anaconda3\lib\site-packages\astroplan\utils.py", line 140, in download_IERS_A
    show_progress=show_progress)

  File "C:\Users\Christian\Anaconda3\lib\site-packages\astropy\utils\data.py", line 1091, in download_file
    raise e

  File "C:\Users\Christian\Anaconda3\lib\site-packages\astropy\utils\data.py", line 1024, in download_file
    with urllib.request.urlopen(remote_url, timeout=timeout) as remote:

  File "C:\Users\Christian\Anaconda3\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)

  File "C:\Users\Christian\Anaconda3\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)

  File "C:\Users\Christian\Anaconda3\lib\urllib\request.py", line 543, in _open
    '_open', req)

  File "C:\Users\Christian\Anaconda3\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)

  File "C:\Users\Christian\Anaconda3\lib\urllib\request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)

  File "C:\Users\Christian\Anaconda3\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)

URLError: <urlopen error [Errno 11002] getaddrinfo failed>
________________________________________________________________________________________________

Additionally, we have encountered two machines that finished executing the program after experiencing this issue. For example, line 32 of the code was run in the iPython window of Spyder giving the following output after roughly 15-20 minutes of execution:

Excerpt from Spyder:
_________________________________________________________________________________________________
In [7]: plot_airmass(betelgeuse, slc, time, brightness_shading=True, altitude_yaxis=True)

WARNING: failed to download http://maia.usno.navy.mil/ser7/finals2000A.all and http://toshi.nofs.navy.mil/ser7/finals2000A.all, using local IERS-B: [WinError 10054] An existing connection was forcibly closed by the remote host;<urlopen error [Errno 11001] getaddrinfo failed> [astropy.utils.iers.iers]
WARNING: Tried to get polar motions for times after IERS data is valid. Defaulting to polar motion from the 50-yr mean for those. This may affect precision at the 10s of arcsec level [astropy.coordinates.builtin_frames.utils]
WARNING: (some) times are outside of range covered by IERS table. Assuming UT1-UTC=0 for coordinate transformations. [astropy.coordinates.builtin_frames.utils]
WARNING: failed to download http://maia.usno.navy.mil/ser7/finals2000A.all and http://toshi.nofs.navy.mil/ser7/finals2000A.all, using local IERS-B: <urlopen error [Errno 11001] getaddrinfo failed>;<urlopen error [Errno 11001] getaddrinfo failed> [astropy.utils.iers.iers]
WARNING: OldEarthOrientationDataWarning: For best precision (on the order of arcseconds), you must download an up-to-date IERS Bulletin A table. To do so, run:

from astroplan import download_IERS_A
download_IERS_A()
 [astroplan.utils]
WARNING: failed to download http://maia.usno.navy.mil/ser7/finals2000A.all and http://toshi.nofs.navy.mil/ser7/finals2000A.all, using local IERS-B: <urlopen error [Errno 11001] getaddrinfo failed>;<urlopen error [Errno 11002] getaddrinfo failed> [astropy.utils.iers.iers]
Out[6]: <matplotlib.axes._subplots.AxesSubplot at 0x2361b0d2308> (this was a plot in spyder)
___________________________________________________________________________________________________
￼

**Comment by keflavich** [comment]
This is an error [upstream](https://github.com/astropy/astropy/pull/9863) now solved in astropy; the USNO turned off one of their servers.  There are two workarounds:
(1) Upgrade to astropy 4.0 or 3.2.3 (e.g., `pip install astropy --upgrade`)
(2) Set the URL manually (per [this note](https://github.com/astropy/astropy/issues/9427#issuecomment-562255522)):
```
from astropy.utils import iers
iers.Conf.iers_auto_url.set('ftp://cddis.gsfc.nasa.gov/pub/products/iers/finals2000A.all')
```

**Comment by keflavich** [comment]
See also #448, #433

**Comment by pllim** [comment]
Please report such inconveniences directly to USNO at https://www.usno.navy.mil/USNO/help/requirements-form so they have an idea of the impact of their work.

**Comment by bmorris3** [comment]
As per previous comments this seems to be fixed upstream. @christianhannah – is this resolved?
