### ISSUE TITLE
.to_table() TypeError, possible bug

### ISSUE THREAD

**Issue by rszakats** [astropy/astroplan#456]
Hi!

I have problems with the newer versions of astroplan.
With 0.4 and astropy-3.2  I have no problem, but with 0.7 and 0.7.dev1234 the 
priority_schedule.to_table() method drops the following error:

Traceback (most recent call last):
  File "rc80_scheduler.py", line 447, in <module>
    out_table = priority_schedule.to_table()
  File "/usr/local/lib/python3.7/site-packages/astroplan-0.7.dev1234-py3.7.egg/astroplan/scheduling.py", line 304, in to_table
    u.Quantity(ra), u.Quantity(dec), config],
  File "/usr/local/lib/python3.7/site-packages/astropy/units/quantity.py", line 387, in __new__
    raise TypeError("The value must be a valid Python or "
TypeError: The value must be a valid Python or Numpy numeric type.

I use python3.7 and astropy-4.0.

I managed to circumvent the problem by changing the code in 
/usr/local/lib/python3.7/site-packages/astroplan-0.7.dev1234-py3.7.egg/astroplan/scheduling.py
in line 303 to:

return Table([target_names, start_times, end_times, durations, ra, dec, config],
                     names=('target', 'start time (UTC)', 'end time (UTC)',
                            'duration (minutes)', 'ra', 'dec', 'configuration'))

It seems the ra,dec unit conversion (u.Quantity(ra), u.Quantity(dec)) caused the problem.

**Comment by T0T4R4** [comment]
Yes I confirm **this is a bug**, it does not occur if the parameters `show_transitions`, `show_unused `are set to `False`, only if one of these is set to `true`.

**Comment by wtgee** [comment]
Hi @Vincentbruga, I just went through the examples in the docs and it seems to work fine when I add the `show_transitions=True` and/or `show_unused=True`. The line mentioned by the OP has also already been changed.

If you are having problems can you post the code and version of python and astropy you are using? Thanks!

**Comment by sagesanto** [comment]
I'm having a similar problem in astropy version 0.8, python 3.10.7, astropy both 5.2.2 and 5.3. 
Though I can see it's been [changed in the github](https://github.com/astropy/astroplan/blob/main/astroplan/scheduling.py#L307), locally line 303 still reads 
`return Table([target_names, start_times, end_times, durations,
                      u.Quantity(ra), u.Quantity(dec), config],
                     names=('target', 'start time (UTC)', 'end time (UTC)',
                            'duration (minutes)', 'ra', 'dec', 'configuration'))`
Pip says astroplan doesn't need an update, but I guess it's wrong. I ran the astroplan tests; the results are [here](https://pastebin.com/tTM8TMUT) if that's helpful in fingerprinting what release I actually have. Thanks!
