### ISSUE TITLE
install failure during testing

### ISSUE THREAD

**Issue by rbiswas4** [astropy/astroplan#463]
I am having trouble installing `astroplan` through pip on a computer which does not have `astropy-helpers` installed. (This is for continuous integration). The linux version is  Ubuntu
  18.04.4
  LTS,
python version is  python-version: 3.7 (although I had similar results in 3.6 and 3.8) 

The error message is below. Could this be an `astropy-helpers` issue and should I report the issue there instead? Thanks!
 
```
    File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/opt/hostedtoolcache/Python/3.7.8/x64/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp2eno0lxx', '--quiet', '--index-url', 'https://pypi.python.org/simple', 'astropy-helpers==2.0.11']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dnv_feey/astroplan/setup.py", line 8, in <module>
        import ah_bootstrap
      File "/tmp/pip-install-dnv_feey/astroplan/ah_bootstrap.py", line 957, in <module>
        BOOTSTRAPPER = _Bootstrapper.main()
      File "/tmp/pip-install-dnv_feey/astroplan/ah_bootstrap.py", line 276, in main
        bootstrapper.run()
      File "/tmp/pip-install-dnv_feey/astroplan/ah_bootstrap.py", line 358, in run
        dist = method()
      File "/tmp/pip-install-dnv_feey/astroplan/ah_bootstrap.py", line 426, in get_local_directory_dist
        upgrade = self._do_upgrade(dist)
      File "/tmp/pip-install-dnv_feey/astroplan/ah_bootstrap.py", line 606, in _do_upgrade
        return self._do_download(version=upgrade.version)
      File "/tmp/pip-install-dnv_feey/astroplan/ah_bootstrap.py", line 591, in _do_download
        raise Exception(msg.format(DIST_NAME, source, repr(e)))
    Exception: Error retrieving astropy-helpers from PyPI:
    DistutilsError("Command '['/opt/hostedtoolcache/Python/3.7.8/x64/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp2eno0lxx', '--quiet', '--index-url', 'https://pypi.python.org/simple', 'astropy-helpers==2.0.11']' returned non-zero exit status 1.")
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
##[error]Process completed with exit code 1.

```

**Comment by bmorris3** [comment]
Hi @rbiswas4,

astroplan no longer relies on `astropy_helpers`, would you please try installing the latest version and let me know if you have any problems? Thanks!
