### ISSUE TITLE
is_event_observable broadcasting problem

### ISSUE THREAD

**Issue by ExoRob** [astropy/astroplan#472]
I'm running this line:

```
is_event_observable(constraints, observer, target, times=midtransit_times)
```

constraints is a list, target is a FixedTarget and mid transit_times is a vector time of size 1.

This causes the following error:

```
Traceback (most recent call last):
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astropy/coordinates/attributes.py", line 111, in __get__
    out = out._apply(np.broadcast_to, shape=instance_shape,
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astropy/time/core.py", line 1447, in _apply
    jd1 = apply_method(jd1)
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astropy/time/core.py", line 1437, in <lambda>
    apply_method = lambda array: method(array, *args, **kwargs)
  File "<__array_function__ internals>", line 5, in broadcast_to
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/numpy/lib/stride_tricks.py", line 180, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/numpy/lib/stride_tricks.py", line 118, in _broadcast_to
    raise ValueError('cannot broadcast a non-scalar to a scalar array')
ValueError: cannot broadcast a non-scalar to a scalar array

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/robertwells/Desktop/saint-ex-science/obs-plan.py", line 115, in <module>
    _ = is_event_observable(constraints, observer, target, times=midtransit_times)
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astroplan/constraints.py", line 1068, in is_event_observable
    applied_constraints = [constraint(observer, target, times=times,
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astroplan/constraints.py", line 1068, in <listcomp>
    applied_constraints = [constraint(observer, target, times=times,
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astroplan/constraints.py", line 264, in __call__
    result = self.compute_constraint(times, observer, targets)
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astroplan/constraints.py", line 480, in compute_constraint
    solar_altitude = self._get_solar_altitudes(times, observer, targets)
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astroplan/constraints.py", line 466, in _get_solar_altitudes
    altaz = observer.altaz(times, get_sun(times))
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astroplan/observer.py", line 496, in altaz
    return target.transform_to(altaz_frame)
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astropy/coordinates/sky_coordinate.py", line 618, in transform_to
    new_coord = trans(self.frame, generic_frame)
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astropy/coordinates/transformations.py", line 1392, in __call__
    curr_coord = t(curr_coord, curr_toframe)
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astropy/coordinates/transformations.py", line 995, in __call__
    return supcall(fromcoord, toframe)
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astropy/coordinates/builtin_frames/cirs_observed_transforms.py", line 44, in cirs_to_altaz
    loccirs = altaz_frame.location.get_itrs(cirs_coo.obstime).transform_to(cirs_coo)
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astropy/coordinates/earth.py", line 644, in get_itrs
    return ITRS(x=self.x, y=self.y, z=self.z, obstime=obstime)
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astropy/coordinates/baseframe.py", line 601, in __init__
    values[fnm] = getattr(self, fnm)
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astropy/coordinates/attributes.py", line 117, in __get__
    raise ValueError(
ValueError: attribute obstime should be scalar or have shape (), but is has shape (1,) and could not be broadcast.
```

The problem goes away if I take the first index of midtransit_times; i.e. mid transit_times[0].

I am using the most recent astropy and astroplan.

**Comment by bmorris3** [comment]
Hi @ExoRob!

I'm using astropy 4.0.1, astroplan 0.6, and I'm not getting the error when I run the following command: 

```python
from astroplan import is_event_observable, FixedTarget, Observer
from astroplan.constraints import AirmassConstraint, AltitudeConstraint
from astroplan.periodic import EclipsingSystem
import astropy.units as u
from astropy.time import Time


period = 10 * u.day
t0 = Time('2020-01-01')
obs = Observer.at_site('Keck')
target = FixedTarget.from_name('Sirius')

es = EclipsingSystem(t0, period)
midtransit = es.next_primary_eclipse_time(t0, n_eclipses=1)

constraints = [AirmassConstraint(max=2.5), AltitudeConstraint(min=30*u.deg)]

b = is_event_observable(constraints, obs, target, times=midtransit)

print(b)
```

I'm wondering if your constraints are actually the problem – what are the constraints being called in your command?

**Comment by ExoRob** [comment]
I tried running your example and it runs fine for me too.

My constraints are below, and do cause the error. It seems AtNightConstraint.twilight_civil() is the problem.

```
constraints = [AtNightConstraint.twilight_civil(), AirmassConstraint(max=1.6)]
```

**Comment by bmorris3** [comment]
So just to be sure, the following script is failing on your machine? It works on mine: 

```
from astroplan import is_event_observable, FixedTarget, Observer
from astroplan.constraints import AirmassConstraint, AtNightConstraint
from astroplan.periodic import EclipsingSystem
import astropy.units as u
from astropy.time import Time

period = 10 * u.day
t0 = Time('2020-01-01')
obs = Observer.at_site('Keck')
target = FixedTarget.from_name('Sirius')

es = EclipsingSystem(t0, period)
midtransit = es.next_primary_eclipse_time(t0, n_eclipses=1)

constraints = [AtNightConstraint.twilight_civil(), AirmassConstraint(max=1.6)]

b = is_event_observable(constraints, obs, target, times=midtransit)

print(b)
```

**Comment by ExoRob** [comment]
Yes, running that code causes:

```
Traceback (most recent call last):
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astropy/coordinates/attributes.py", line 111, in __get__
    out = out._apply(np.broadcast_to, shape=instance_shape,
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astropy/time/core.py", line 1447, in _apply
    jd1 = apply_method(jd1)
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astropy/time/core.py", line 1437, in <lambda>
    apply_method = lambda array: method(array, *args, **kwargs)
  File "<__array_function__ internals>", line 5, in broadcast_to
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/numpy/lib/stride_tricks.py", line 180, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/numpy/lib/stride_tricks.py", line 118, in _broadcast_to
    raise ValueError('cannot broadcast a non-scalar to a scalar array')
ValueError: cannot broadcast a non-scalar to a scalar array

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/robertwells/Desktop/astroplan-testing.py", line 17, in <module>
    b = is_event_observable(constraints, obs, target, times=midtransit)
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astroplan/constraints.py", line 1068, in is_event_observable
    applied_constraints = [constraint(observer, target, times=times,
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astroplan/constraints.py", line 1068, in <listcomp>
    applied_constraints = [constraint(observer, target, times=times,
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astroplan/constraints.py", line 264, in __call__
    result = self.compute_constraint(times, observer, targets)
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astroplan/constraints.py", line 480, in compute_constraint
    solar_altitude = self._get_solar_altitudes(times, observer, targets)
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astroplan/constraints.py", line 466, in _get_solar_altitudes
    altaz = observer.altaz(times, get_sun(times))
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astroplan/observer.py", line 496, in altaz
    return target.transform_to(altaz_frame)
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astropy/coordinates/sky_coordinate.py", line 618, in transform_to
    new_coord = trans(self.frame, generic_frame)
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astropy/coordinates/transformations.py", line 1392, in __call__
    curr_coord = t(curr_coord, curr_toframe)
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astropy/coordinates/transformations.py", line 995, in __call__
    return supcall(fromcoord, toframe)
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astropy/coordinates/builtin_frames/cirs_observed_transforms.py", line 44, in cirs_to_altaz
    loccirs = altaz_frame.location.get_itrs(cirs_coo.obstime).transform_to(cirs_coo)
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astropy/coordinates/earth.py", line 644, in get_itrs
    return ITRS(x=self.x, y=self.y, z=self.z, obstime=obstime)
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astropy/coordinates/baseframe.py", line 601, in __init__
    values[fnm] = getattr(self, fnm)
  File "/Users/robertwells/anaconda3/envs/py38/lib/python3.8/site-packages/astropy/coordinates/attributes.py", line 117, in __get__
    raise ValueError(
ValueError: attribute obstime should be scalar or have shape (), but is has shape (1,) and could not be broadcast.
```

I'm using astroplan 0.6 and astropy 4.1rc1. I can try to reinstall them?

**Comment by bmorris3** [comment]
This appears to be related to astropy/astropy#5982 and the solution might be in https://github.com/astropy/astropy/pull/10424.

To fix this locally, can you try installing astropy from source on your machine like this? 
```
pip uninstall astropy
git clone https://github.com/astropy/astropy.git
cd astropy
python setup.py install
```

**Comment by ExoRob** [comment]
Thanks Brett. I re-installed astropy, which is now version 4.0.1.post1 and it no longer errors.

**Comment by bmorris3** [comment]
Great, closing.
