### ISSUE TITLE
pushing astroplan-0.7.dev1245 to pipy

### ISSUE THREAD

**Issue by simeonreusch** [astropy/astroplan#485]
Hi everyone,
would it be possible to push the newest version (astroplan-0.7.dev1245) to pipy (as developer release), because it fixes the incompatibility with the newest astropy release? This would be great!

**Comment by simontorres** [comment]
I'm also experiencing errors that I think are related with this issue.

```
======================================================================
ERROR: goodman_pipeline (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: goodman_pipeline
Traceback (most recent call last):
  File "/user/simon/anaconda3/envs/goodman_pipeline/lib/python3.8/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/user/simon/anaconda3/envs/goodman_pipeline/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/data/simon/development/soar/goodman_pipeline/goodman_pipeline/__init__.py", line 5, in <module>
    from . import spectroscopy
  File "/data/simon/development/soar/goodman_pipeline/goodman_pipeline/spectroscopy/__init__.py", line 5, in <module>
    from .redspec import MainApp, get_args
  File "/data/simon/development/soar/goodman_pipeline/goodman_pipeline/spectroscopy/redspec.py", line 17, in <module>
    from .wavelength import WavelengthCalibration
  File "/data/simon/development/soar/goodman_pipeline/goodman_pipeline/spectroscopy/wavelength.py", line 28, in <module>
    from ..core import (add_linear_wavelength_solution,
  File "/data/simon/development/soar/goodman_pipeline/goodman_pipeline/core/__init__.py", line 5, in <module>
    from .core import (GenerateDcrParFile,
  File "/data/simon/development/soar/goodman_pipeline/goodman_pipeline/core/core.py", line 23, in <module>
    from astroplan import Observer
  File "/user/simon/anaconda3/envs/goodman_pipeline/lib/python3.8/site-packages/astroplan/__init__.py", line 23, in <module>
    from .utils import *
  File "/user/simon/anaconda3/envs/goodman_pipeline/lib/python3.8/site-packages/astroplan/utils.py", line 15, in <module>
    from astropy.utils.data import _get_download_cache_locs, CacheMissingWarning
ImportError: cannot import name '_get_download_cache_locs' from 'astropy.utils.data' (/user/simon/anaconda3/envs/goodman_pipeline/lib/python3.8/site-packages/astropy/utils/data.py)


----------------------------------------------------------------------
Ran 1 test in 0.000s
```

**Comment by simeonreusch** [comment]
Yes this will be resolved when the latest merge is pushed to pypi. I would do that myself, but obviously don‘t have the rights to do so.

**Comment by wtgee** [comment]
Thanks, I'm trying to figure out the process to make this happen. @bmorris3?

**Comment by simontorres** [comment]
This process can be automated easily with github actions.

take a look at this. 
https://github.com/soar-telescope/goodman_pipeline/blob/master/.github/workflows/python-publish.yml

I'm available to help if needed.

**Comment by wtgee** [comment]
> This process can be automated easily with github actions.
> 
> take a look at this.
> https://github.com/soar-telescope/goodman_pipeline/blob/master/.github/workflows/python-publish.yml
> 
> I'm available to help if needed.

Thanks @simontorres. Mostly I'm trying to figure out the astropy chain-of-command process to make this happen, not the technical one. :grin: I'd definitely like to get some of the testing and releasing on some GHA if possible

@eteq any advice on the process of getting a release? I have triage permissions now but am not part of the release loop. Thanks!

**Comment by bmorris3** [comment]
@wtgee @simontorres, et al.: I'll try to get the release done tonight! Sorry for the delay.

**Comment by simontorres** [comment]
@bmorris3 Thank you very much and no worries, we understand :)

**Comment by simeonreusch** [comment]
Good morning, any luck with this? :-)

**Comment by bmorris3** [comment]
v0.7 uploaded to pypi 5 minutes ago :tada:.
