### ISSUE TITLE
Looking ofr dusks/dawns along a year : TargetNeverUpWarning lead to crash

### ISSUE THREAD

**Issue by tstolarczyk** [astropy/astroplan#508]
Hello,

Astroplan v0.8

I am making the list of dusks and dawns along the year 2021 with the code below.
It crashes on June the 11th because of a too-short night it seems, which is likely to happen every year :-)
Any workaround to suggest?
Thanks !!!

```
from astropy.time import Time
import astropy.units as u

from astropy.coordinates import EarthLocation
from astroplan import Observer
```
```
twindow = [Time("2021-06-01 00:00:00.0",scale="utc"),
           Time("2021-12-31 23:59:59.0",scale="utc")]
tstart = twindow[0]
tstop = twindow[1]
location = EarthLocation.of_address("Paris")

obs   = Observer(location  = location, name = location, timezone ="utc")
night = obs.is_night(tstart, horizon = -18*u.deg)

if (night): search = "previous" # Will search start of that night
else:       search = "next"     # Will search next night

t_night=[]

t_dawn = tstart # First dawwn cannot be before start
while(t_dawn < tstop):
        t_dusk = obs.twilight_evening_astronomical(t_dawn, which = search)
        print(" dusk :",t_dusk.datetime)
        search="next"
        t_dawn = obs.twilight_morning_astronomical(t_dusk, which="next")
        print(" dawn :",t_dawn.datetime)
        t_night.append([t_dusk, t_dawn])
```
Here is the Error message:
 ```
WARNING: TargetNeverUpWarning: Target with index 0 does not cross horizon=-18.0 deg within 24 hours [astroplan.observer]
WARNING: ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)" [astropy._erfa.core]
Traceback (most recent call last):

  File "\\dapdc5\stolar\My Documents\CTA\Analysis\C14\skylab.py", line 471, in <module>
    tnights, _= because_the_night(location, twindow=twindow, ax=ax,alpha=0.1)

  File "\\dapdc5\stolar\My Documents\CTA\Analysis\C14\skylab.py", line 196, in because_the_night
    print(" dusk :",t_dusk.datetime)

  File "C:\Users\stolar\AppData\Local\Continuum\anaconda3\gpy0.17\lib\site-packages\astropy\time\core.py", line 1718, in __getattr__
    return self.to_value(attr, subfmt=None)

  File "C:\Users\stolar\AppData\Local\Continuum\anaconda3\gpy0.17\lib\site-packages\astropy\time\core.py", line 1007, in to_value
    parent=tm, **kwargs))

  File "C:\Users\stolar\AppData\Local\Continuum\anaconda3\gpy0.17\lib\site-packages\astropy\time\formats.py", line 884, in to_value
    out[...] = datetime.datetime(iy, im, id, ihr, imin, isec, ifracsec)

ValueError: year -4713 is out of range
```

**Comment by bmorris3** [comment]
Hi @tstolarczyk,

As I just wrote in #511, I think this won't be a problem if the time you use as a reference time is centered closer to local noon. As you suggest, this occurs when the querying time is very close to a rise/set, and can be avoided if you start your `tstart` variable at a time further from dawn/dusk.

Does that help?
